name: block_pushing_lowdim

obs_dim: 16
action_dim: 2
keypoint_dim: 2
obs_eef_target: True

env_runner: 
  _target_:  irrep_actions.env_runner.block_pushing_lowdim_runner.BlockPushingLowdimRunner
  num_train: 6
  num_train_vis: 2
  train_start_seed: 0
  num_test: 50
  num_test_vis: 4
  test_start_seed: 100000
  max_steps: 350
  num_obs_steps: ${num_obs_steps}
  num_action_steps: ${num_action_steps}
  fps: 5
  past_action: ${past_action_visible}
  abs_action: False
  num_envs: null

dataset:
  _target_: irrep_actions.dataset.block_pushing_lowdim_dataset.BlockPushingLowdimDataset
  path: data/block_pushing/multimodal_push_seed.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${num_obs_steps}-1'}
  pad_after: ${eval:'${num_action_steps}-1'}
  obs_eef_target: True
  seed: 0
  harmonic_action: ${is_harmonic}
  val_ratio: 0.02
