name: pusht_image

image_dim: &image_dim [3, 96, 96]
action_dim: 2
# shape_meta: {{'obs': [3, 96, 96]}}
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: *image_dim #[3, 96, 96]
      type: rgb
  action:
    shape: [2]

env_runner:
  _target_: fvf.env_runner.pusht_image_runner.PushTImageRunner
  num_train: 6
  num_train_vis: 2
  train_start_seed: 0
  num_test: 50
  num_test_vis: 4
  test_start_seed: 100000
  max_steps: 300
  num_obs_steps: ${num_obs_steps}
  num_action_steps: ${num_action_steps}
  num_latency_steps: ${num_latency_steps}
  fps: 10
  past_action: ${past_action_visible}
  num_envs: null
  legacy: False
  action_coords: ${action_coords}

dataset:
  _target_: fvf.dataset.pusht_image_dataset.PushTImageDataset
  path: data/pusht_100 # fourier_value_functions/
  horizon: ${horizon}
  pad_before: ${eval:'${num_obs_steps}-1+${num_latency_steps}'}
  pad_after: ${eval:'${num_action_steps}-1'}
  seed: 0
  action_coords: ${action_coords}
  val_ratio: 0.02
  max_train_episodes: 90
