name: pusht_lowdim 

obs_dim: 20 # 9*2 keypoints + 2 state
action_dim: 2
keypoint_dim: 2
z_dim: 64

dataset:
  _target_: irrep_actions.dataset.lowdim_dataset.LowdimDataset
  path: data/pusht/pusht_cchi_v7_replay.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${num_obs_steps}-1+${num_latency_steps}'}
  pad_after: ${eval:'${num_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
