name: pusht_lowdim 

obs_dim: 38 # 9*2 keypoints + 2 state
action_dim: 2
keypoint_dim: 2

env_runner:
  _target_: imitation_learning.env_runner.pusht_keypoints_runner.PushTKeypointsRunner
  keypoint_visible_rate: ${keypoint_visible_rate}
  num_train: 10
  num_train_vis: 2
  train_start_seed: 0
  num_test: 50
  num_test_vis: 4
  test_start_seed: 100000
  max_steps: 500
  num_obs_steps: ${num_obs_steps}
  num_action_steps: ${num_action_steps}
  num_latency_steps: ${num_latency_steps}
  fps: 10
  agent_keypoints: False
  past_action: ${past_action_visible}
  num_envs: 30
  random_goal_pose: False

dataset:
  _target_: imitation_learning.dataset.pusht_lowdim_dataset.PushTLowdimDataset
  path: data/pusht_100 
  horizon: ${horizon}
  pad_before: ${eval:'${num_obs_steps}-1+${num_latency_steps}'}
  pad_after: ${eval:'${num_action_steps}-1'}
  seed: 0
  action_coords: ${action_coords}
  val_ratio: 0.02
  max_train_episodes: 90
