name: block_touching 

robot_state_dim: 9
object_state_dim: 3
world_state_len: ${robot_state_len}
action_dim: 2
z_dim: 64

encoder:
  _target_: fail.model.modules.RobotStateObjectPoseEncoder
  robot_state_dim: ${robot_state_dim}
  object_state_dim: ${task.object_state_dim}
  robot_state_len: ${robot_state_len}
  object_state_len: ${world_state_len}
  model_dim: 32
  trans_out_dim: 32
  trans_layers: 4
  trans_heads: 8
  z_dim: ${z_dim}
  dropout: 0.1

so2_encoder:
  _target_: fail.model.modules.SO2RobotStateObjectPoseEncoder
  robot_state_dim: ${robot_state_dim}
  object_state_dim: ${task.object_state_dim}
  robot_state_len: ${robot_state_len}
  object_state_len: ${world_state_len}
  model_dim: 64
  trans_out_dim: 32
  trans_layers: 4
  trans_heads: 8
  L: 3
  z_dim: ${z_dim}
  dropout: 0.1

dataset:
  _target_: fail.dataset.object_state_dataset.ObjectStateDataset
  path: data/block_touching_100
  horizon: ${num_obs_steps}
  pad_before: 0
  pad_after: ${eval:'${num_action_steps}-1'}
  seed: 0
  val_ratio: 0.02
